name: flutter_inline_webview_macos
description: Flutter plugin for inline display of native WebView on macOS
version: 0.0.7
homepage: https://github.com/akaboshinit/flutter_inline_webview_macos
issue_tracker: https://github.com/akaboshinit/flutter_inline_webview_macos/issues

screenshots:
  - description: 'Examples of the splash screen on iOS.'
    path: images/example.png

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: FlutterInlineWebViewMacosPlugin

